### ISSUE TITLE
Missing info_hash item

### ISSUE THREAD

**Issue by dRaiNe** [eweast/BencodePy#4]
I believe there's an missing item when decoding .torrent file. There should be info_hash of the whole torrent.

**Comment by eweast** [comment]
The info_hash is calculated from the .torrent file's info key; it isn't stored in the file itself ([see the spec](https://wiki.theory.org/BitTorrentSpecification#Metainfo_File_Structure)).

BencodePy doesn't perform this calculation for you because that calculation is unique to the BitTorrent specification whereas BencodePy is independent of any particular usage/intent.

BencodePy does decode to OrderedDict which makes hashing the info key straightforward.

**Comment by dRaiNe** [comment]
You're right.
